spring:
  application:
    name: mooc-gateway
  cloud:
    gateway:
      routes:
      - id: manager-cms-service
        #lb代表从注册中心获取服务
        uri: lb://MANAGER-CMS-SERVICE
        predicates:
        - Path=/api/cms/**
        # 去掉/api/item/前缀
        filters:
        - StripPrefix=2
#      globalcors:
#        cors-configurations:
#          '[/**]':
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/


