spring:
  application:
    name: mooc-gateway
  cloud:
    gateway:
      routes:
      - id: manager-cms-service
        uri: lb://MANAGER-CMS-SERVICE
        predicates:
        - Path=/api/cms/**
        filters:
        - StripPrefix=2
      - id: course-service
        uri: lb://COURSE-SERVICE
        predicates:
        - Path=/api/course/**
        filters:
        - StripPrefix=1
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/


