server:
  port: 6061
spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://47.100.97.46:3306/mooc_course?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://47.100.97.46:27017
      database: mooc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6000/eureka/
